### PR TITLE
Server fix

### PR DESCRIPTION
**Pull request by noobanidus**
I've had a number of Concurrent Modification Exceptions which appear to be a result of the networking thread executing code that accesses entities at the same time as updateTileLightAndEntities (or however it is properly named, I can't remember the order) is firing in the main thread and iterating over the entity list.

My solution was to simply use `addScheduledTask` on the code in question so that it would fire instead in the main thread, after the iteration was complete.

Unfortunately, as the packets were both-ways, it required a little bit of finangling on my part. Most of this is probably due to me failing to properly understand the code base and being used to separate client/server packets. 

If you wish to implement it in a different way, feel free!

I've been testing this thoroughly and extensively on my private multiplayer server and have yet to have a crash while using it, as opposed to irregular crashes previously (always predicated by me attempting to perform a trade).

### CODE REVIEW

**Comment by faceofcat** [comment]
this looks good @duely !

but could you please fix the Codacy issues?... or else the MMD Gods will not be pleased! 😄 

thanks!

**Comment by noobanidus** [comment]
I'm sorry, I'm not sure what you mean by Codacy. Could you clarify for me? I'm perfectly happy to modify the PR in any way you see fit however, so just let me know. (I really, really love this mod!)

**Comment by noobanidus** [comment]
Oh, I didn't realise that this was codacy. Amusingly, the unused import is my issue, but the unscoped/"package private" static function is actually me just following the standards of what was already included in the mod. If you wish me to adjust it, I shall.

**Comment by faceofcat** [comment]
sure... not saying existing code is perfect 😄 😄 

but all new code should try to follow some standards... so... would be nice if you could change that.

**Comment by noobanidus** [comment]
I've removed the unused import. If you want to refactor the project to use explicit scoping, then by all means go ahead. It is quite literally outside of the scope of my PR to change the scope of your existing functions to match a standard; if you wish to do so after merging, by all means go ahead -- I have no objections otherwise I wouldn't be submitting the PR in the first place.

**Comment by faceofcat** [comment]
sounds good to me... :)

hey, do you happen to have a curse forge account?

**Comment by noobanidus** [comment]
(Unless I misunderstood and you were specifically referring to the function I added, given that it was an overload I don't think there's any way for me to give it a different scope. Apologies if I came across a bit grumpy, I just realised now that you weren't asking me to rescope all your code for you).

I do have a CurseForge account, it's Noobanidus.

**Comment by faceofcat** [comment]
this should fix #1, #4 and #9 ... right?

**Comment by noobanidus** [comment]
Yes, given I have not encountered any other CME errors/crashes when using it, and have been using it extensively, those can definitely be marked as resolved. (It's only because HellfirePvP has been helping out with advising on some network-related things, and then I reported a telescope-related CME and saw his fix, then encountered this and dove into the code, that I realised what the problem was.)

**Pull request merged**
